repository:
  name: fabric-test
  description: A collection of utilities used to test the core Hyperledger Fabric
    projects
  homepage: ''
  default_branch: main
  has_downloads: true
  has_issues: false
  has_projects: false
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
