pull_request_rules:
  - name: Auto-Merge on Approving Label and Changes Limited to tools/chaincode-integration/ Folder
    conditions:
      - files~=^tools/chaincode-integration/
      - -files~=^(?!^tools/chaincode-integration).*
      - label=merge-ready
    actions:
      merge:
        method: rebase
