# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)

trigger: none
pr: none
schedules:
  - cron: "0 1 * * *" # 20:00 EST / 01:00 UTC
    displayName: Daily midnight build
    branches:
      include:
        - master
        - release-2.*
        - release-1.4
    always: "true"

variables:
  - group: Azure
  - name: GOBIN
    value: $(Agent.BuildDirectory)/go/bin
  - name: GOPATH
    value: $(Agent.BuildDirectory)/go
  - name: PATH
    value: $(Agent.BuildDirectory)/go/bin:$(Agent.BuildDirectory)/go/src/github.com/hyperledger/fabric-test/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
  - name: GO_VER
    value: 1.13.8
  - name: NODE_VER
    value: 10.17.0
  - name: BRANCH
    value: release-2.0
  - name: RELEASE
    value: 2.0.2-stable
  - name: TWO_DIGIT_RELEASE
    value: 2.0-stable

jobs:
  - job: TestAndPublish
    pool:
      vmImage: ubuntu-18.04
    steps:
      - template: templates/install_deps.yml
      - template: templates/install_deps_byfn.yml
      - script: mkdir -p ${GOBIN}
        displayName: Create GOBIN
      - script: make build/fabric build/fabric-ca build/fabric-chaincode-java build/fabric-chaincode-node
        displayName: Build Docker Images
      - script: make regression/publish
        displayName: Run Tests
      - script: ./ci/scripts/trigger_publish_artifacts.sh
        displayName: Publish Docker Images
        env:
          ARTIFACTORY_USERNAME: $(ARTIFACTORY_USERNAME)
          ARTIFACTORY_PASSWORD: $(ARTIFACTORY_PASSWORD)
