# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0


name: Fabric-Test-Weekly-$(Date:yyyyMMdd)
trigger: none
pr: none
schedules:
  # 3 AM UTC/10 PM EST on every Friday
  - cron: "0 3 * * FRI"
    displayName: 'Fabric Test Weekly Job'
    branches:
      include:
        - master
    always: true

variables:
  FABRIC_CFG_PATH: $(Agent.BuildDirectory)/go/src/github.com/hyperledger/fabric-test/config/
  GO_BIN: $(Agent.BuildDirectory)/go/bin
  GO_PATH: $(Agent.BuildDirectory)/go
  GO_VER: 1.14.2
  NODE_VER: 12.15.0
  PATH: $(Agent.BuildDirectory)/go/bin:$(Agent.BuildDirectory)/go/src/github.com/hyperledger/fabric-test/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
stages:
  - stage: Upgrade
    dependsOn: []
    displayName: Upgrade Network
    pool:
      vmImage: ubuntu-18.04
    jobs:
      - job: Weekly
        pool:
          vmImage: ubuntu-18.04
        timeoutInMinutes: 360
        steps:
        - checkout: self
          path: 'go/src/github.com/hyperledger/fabric-test'
          displayName: Checkout Fabric Test Code
        - template: templates/install_deps.yml
        - script: make upgrade
          displayName: Run Scenario
