# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
- name: Get start timestamp
  hosts: cloud
  connection: local
  tasks:
    - set_fact:
        starttime: "{{ ansible_date_time }}"

- name: Run the plays
  vars:
    pjroot: "{{ playbook_dir }}/../../../../cello/src/agent/ansible/"
  import_playbook: "roles/tool_{{ tool_type | default('pte') }}/plays.yml"

- name: inform the installer
  hosts: cloud
  connection: local
  tasks:
    - debug:
        msg: >-
          The work load started at {{ hostvars.cloud.starttime.time }},
          ended at {{ ansible_date_time.time }}
