# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: Daily Upgrade

on:
  workflow_dispatch:
  schedule:
    - "0 3 * * *"

env:
  GO_VER: 1.15.8
  NODE_VER: 12.15.0

  FABRIC_CFG_PATH: ${{ github.workspace }}/go/src/github.com/hyperledger/fabric-test/config
  GOPATH: ${{ github.workspace }}/go
  PATH: ${{ github.workspace }}/go/bin:/bin:${{ github.workspace }}/go/src/github.com/hyperledger/fabric-test/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

defaults:
  run:
    working-directory: go/src/github.com/hyperledger/fabric-test

jobs:
  upgrade-2_2:
    name: Upgrade Network
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VER }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VER }}
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: go/src/github.com/hyperledger/fabric-test
      - name: Run Upgrade Tests
        run: make upgrade2.2

  upgrade-1_4-2_2:
    name: Upgrade 1.4 Directly to 2.2 Network
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VER }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VER }}
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: go/src/github.com/hyperledger/fabric-test
      - name: Run Upgrade Tests
        run: make upgrade1.4to2.2
