# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: Pull Request

on:
  pull_request:
    paths-ignore:
      - tools/chaincode-integration/*
  push:
    paths-ignore:
      - tools/chaincode-integration/*

env:
  GO_VER: 1.15.8
  NODE_VER: 12.15.0
  FABRIC_CFG_PATH: ${{ github.workspace }}/config
  GOPATH: /tmp/go
  PATH: /tmp/go/bin:/bin:${{ github.workspace }}/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

jobs:
  verify:
    name: Verify Build
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VER }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Linter
        run: make lint
      - name: Run Unit Tests
        run: make unit-tests

  smoke:
    name: Smoke Network
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VER }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VER }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Smoke Network Tests
        run: make regression/smoke

  basic:
    name: Basic Network
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VER }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VER }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Basic Network Tests
        run: make regression/basicnetwork
